### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "205@gmail.com",
  "password" : "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=90bb26d2a-275c-45c5-8a80-376043c6c84a